nc: 3
names: ['FireExtinguisher', 'ToolBox', 'OxygenTank']
train: /content/dataset/HackByte_Dataset/data/train
val: /content/dataset/HackByte_Dataset/data/val
test: /content/dataset/HackByte_Dataset/data/test